version: '3.8'
services:
  accounts:
    container_name: msaccounts
    build: ./accounts
    volumes:
      - ./accounts/code:/usr/src/app
    networks:
      - msanxietyally
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msanxietyally
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  questionnaire:
    container_name: questionnaire
    build: ./questionnaire
    volumes:
      - ./questionnaire/code:/usr/src/app
    networks:
      - msanxietyally
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
networks:
  msanxietyally:
    driver: bridge